GUT-138: Story module updates
penske-media-corp/pmc-larva pull request #366
Opened 2021-07-14 18:17 UTC by ethitter

### Doneness Checklist:

Pre-release # (or n/a):

- [ ] Updated changelog with summary of changes under `Unpublished` section
- [ ] `npm run prod` in this repo outputs no changes
- [ ] Tested changes in pmc-spark [via a pre-release](https://confluence.pmcdev.io/x/XhOeAw):
- - [ ] If changes to build tools: npm scripts `prod`, `lint`, and `dev` scripts run as expected
- - [ ] If changes to Larva server: Static site generates as expected in a theme  (avail. on a URL {brand}.stg.larva.pmcdev.io)

2021-07-22 12:51 UTC, laras126 requested changes
A few syntax updates required in the controller files – we don't have linting for these yet, but will someday.

2021-07-22 12:51 UTC, laras126 commented on packages/larva-patterns/modules/story/story.center-vertical.js
> +const horizontal_alignment = ' lrv-u-justify-content-center';
These controller files should be kept as simple as possible - someday we will decide on a better syntax for them, and can create codemods or similar to replace with the new syntax. For that reason, add classes directly in the assignment to the object property vs. controlling redundancy with a variable, to keep the syntax as simple and consistent as possible.

A linter for these files to automate rules such as this that are currently in my brain only is part of the Larva Rollout, and now has a ticket - https://jira.pmcdev.io/browse/GUT-186 – but will be pretty low priority.

2021-07-22 12:51 UTC, laras126 commented on packages/larva-patterns/modules/story/story.right.js
> +const horizontal_alignment = ' lrv-u-justify-content-end';
No variable - write the class in line.

2021-07-22 12:51 UTC, laras126 commented on packages/larva-patterns/modules/story/story.right.js
> +story_right.story_grid_primary_classes = story_right.story_grid_primary_classes.replace(
Copy/paste to reassign the entire value with the replaced string - no `.replace`. Allowing the use of array and string manipulation methods resulted in the incredible maze that is known as the VY code-base. It's redundant, yes, but definitely preferable to that.

2021-07-22 12:51 UTC, laras126 commented on packages/larva-patterns/modules/story/story.vertical.js
> +story_vertical.story_grid_classes = story_vertical.story_grid_classes.replace(
No `.replace` in this file. 

This is a method we would disallow in the linter.

2021-07-22 20:28 UTC, ethitter commented
@laras126 - thanks for the feedback! This is ready for another review

2021-07-22 20:56 UTC, laras126 commented
@ethitter Code looks good but please check the Doneness checklist! Really just the CHANGELOG one is relevant here.

2021-07-23 15:42 UTC, ethitter commented
@laras126 - updates made, this is ready for another look

2021-07-23 15:55 UTC, laras126 approved these changes
All good, thanks!

2021-07-23 16:40 UTC, merged