RS Header: PMCP-3704 & PMCP-3777 & PMCP-3776 & PMCP-3778
penske-media-corp/pmc-larva pull request #527
Opened 2022-04-21 10:19 UTC by prajapatisagar

### Make sure you complete these items:

- [ ] Updated root CHANGELOG.md with summary of changes under `Unpublished` section
- [ ] `npm run prod` in this repo outputs expected changes (excepting the issue with re-ordered partials in larva-css algorithms partials - see [LRVA-1885](https://jira.pmcdev.io/browse/LRVA-1885))
- [ ] If adding a new pattern, in the PR comment, included a screenshot and link to the static Vercel deployment
- [ ] If changes to build scripts or the Node.js server, tested changes in pmc-spark [via a pre-release](https://confluence.pmcdev.io/x/XhOeAw)
- - If changes to build tools: npm scripts `prod`, `lint`, and `dev` scripts run as expected
- - If changes to Larva server: Static site generates as expected in a theme  (avail. on a URL {brand}.stg.larva.pmcdev.io)

2022-04-27 14:28 UTC, laras126 commented on packages/larva-css/src/03-utilities/u-font-size.common.inline.scss
> +.lrv-u-font-size-8\@mobile-max {
Can this be incorporated into a token for lrv-a-font?

2022-04-27 14:39 UTC, laras126 requested changes
Need a couple of updates - particularly to add links to the modules in the PR comment for the reviewers.

2022-04-27 14:39 UTC, laras126 commented on CHANGELOG.md
> +* larva-patterns - Add `expandable-search`, `header-menu`, `header-sticky`, `header`, `search-form`, `read-next` modules.
Please address the checkboxes in the PR comment.

2022-04-27 14:39 UTC, laras126 commented on packages/larva-css/src/04-js/partials/expandable-search.scss
> +// Temporarily disabled until reactor is merged.
What does this mean?

2022-04-27 14:57 UTC, laras126 commented
Hi Sagar - (re-iterating what I wrote in Slack) definitely update the PR with links and screenshots for the added modules, but please wait to remove the very specific CSS values until we have made an official decision about this. Thank you!

2022-05-12 16:32 UTC, vtellapmc approved these changes

2022-05-12 16:44 UTC, merged