Feature/pmcp 3790 - Add the-moth variant for content-showcase module
penske-media-corp/pmc-larva pull request #530
Opened 2022-04-26 20:08 UTC by anischarolia-multidots

### Make sure you complete these items:

- [X] Updated root CHANGELOG.md with summary of changes under `Unpublished` section
- [X] `npm run prod` in this repo outputs expected changes (excepting the issue with re-ordered partials in larva-css algorithms partials - see [LRVA-1885](https://jira.pmcdev.io/browse/LRVA-1885))
- [X] If adding a new pattern, in the PR comment, included a screenshot and link to the static Vercel deployment
- [ ] If changes to build scripts or the Node.js server, tested changes in pmc-spark [via a pre-release](https://confluence.pmcdev.io/x/XhOeAw)
- - If changes to build tools: npm scripts `prod`, `lint`, and `dev` scripts run as expected
- - If changes to Larva server: Static site generates as expected in a theme  (avail. on a URL {brand}.stg.larva.pmcdev.io)

2022-04-26 20:09 UTC, anischarolia-multidots commented
New variant added for content-showcase module:
https://pmc-larva-git-feature-pmcp-3790-penske-media-corp.vercel.app/larva/modules/content-showcase/the-moth

2022-04-26 22:35 UTC, vtellapmc requested changes

2022-04-26 22:35 UTC, vtellapmc commented on CHANGELOG.md
> +* larva-css - Add utility classes for `width`, `overflow` and `flex-shrink`.
This needs to be added under ## Unpublished

2022-04-28 19:07 UTC, vtellapmc requested changes

2022-04-28 19:07 UTC, vtellapmc commented on packages/larva-css/src/03-utilities/u-width.common.inline.scss
> +}
These need to be moved to theme since they are theme specific.

2022-05-17 04:52 UTC, merged