PMCP-3789: Add `lrv-a-crop-1x1\@mobile-max` classes.
penske-media-corp/pmc-larva pull request #537
Opened 2022-05-06 10:56 UTC by akashdhawade2005

- Add `lrv-a-crop-1x1\@mobile-max` class. 
- Fix issue with `lrv-a-truncate-ellipsis-5line` class.

### Make sure you complete these items:

- [x] Updated root CHANGELOG.md with summary of changes under `Unpublished` section
- [x] `npm run prod` in this repo outputs expected changes (excepting the issue with re-ordered partials in larva-css algorithms partials - see [LRVA-1885](https://jira.pmcdev.io/browse/LRVA-1885))
- [ ] If adding a new pattern, in the PR comment, included a screenshot and link to the static Vercel deployment
- [ ] If changes to build scripts or the Node.js server, tested changes in pmc-spark [via a pre-release](https://confluence.pmcdev.io/x/XhOeAw)
- - If changes to build tools: npm scripts `prod`, `lint`, and `dev` scripts run as expected
- - If changes to Larva server: Static site generates as expected in a theme  (avail. on a URL {brand}.stg.larva.pmcdev.io)

2022-05-12 21:43 UTC, vtellapmc requested changes
Changelog file need to be synced. Other than that it looks good to me

2022-05-12 21:43 UTC, vtellapmc commented on CHANGELOG.md
> +
Need to update this file

2022-05-13 14:27 UTC, akashdhawade2005 commented on CHANGELOG.md
> +
@vtellapmc conflict fixed.

2022-05-13 16:35 UTC, vtellapmc approved these changes

2022-05-13 16:37 UTC, merged